[package]
name = "pretty-bytes"
version = "0.2.0"
authors = ["Kohei Hasegawa"]
description = "Convert bytes to a human readable string"
repository = "https://github.com/banyan/rust-pretty-bytes"
license = "MIT"
readme = "README.md"

[dependencies]
getopts = "0.2"
libc = "0.2"
